#include "iir_filter_time_varying/state_variable_filter.h"

DEFINE_ALGORITHM_CONSTRUCTOR(IIRFilterTimeVarying, StateVariableFilter, IIRFilterTimeVaryingConfiguration)

DEFINE_ALGORITHM_CONSTRUCTOR(IIRFilterCascadeTimeVarying, StateVariableFilterCascade, IIRFilterCascadeTimeVaryingConfiguration)