#include "noise_estimation/noise_estimation_activity_detection.h"

DEFINE_ALGORITHM_CONSTRUCTOR(NoiseEstimation, NoiseEstimationActivityDetection, NoiseEstimationConfiguration)

DEFINE_ALGORITHM_CONSTRUCTOR(NoiseEstimationActivity, NoiseEstimationOutputActivityDetection, NoiseEstimationActivityConfiguration)

DEFINE_ALGORITHM_CONSTRUCTOR(NoiseEstimationActivityFused, NoiseEstimationOutputFusedActivityDetection, NoiseEstimationActivityFusedConfiguration)
