#include "interpolation/interpolation_cubic.h"

DEFINE_ALGORITHM_CONSTRUCTOR(InterpolationSample, InterpolationCubicSample, InterpolationSampleConfiguration)
DEFINE_ALGORITHM_CONSTRUCTOR(Interpolation, InterpolationCubic, InterpolationConfiguration)
DEFINE_ALGORITHM_CONSTRUCTOR(InterpolationConstant, InterpolationCubicConstant, InterpolationConstantConfiguration)
