#include "interpolation/interpolation_cubic.h"

DEFINE_CONSTRUCTOR_DESTRUCTOR(InterpolationSample, InterpolationCubicSample, InterpolationSampleConfiguration)
DEFINE_CONSTRUCTOR_DESTRUCTOR(Interpolation, InterpolationCubic, InterpolationConfiguration)
DEFINE_CONSTRUCTOR_DESTRUCTOR(InterpolationConstant, InterpolationCubicConstant, InterpolationConstantConfiguration)
